### ISSUE TITLE
Some more issues

### ISSUE THREAD

**Issue by jezzen** [Fundryi/Destiny#13]
Not sure if Fundryi can check the boxes as they are done for the next version? But I'll have them as a checklist anyways.

- [x] Beginner bad guys quest not detecting mob kills for some reason
- [x] Several core mods that are currently unused (AppleCore, CsokiCraftUtil, InfinityLib, IVToolKit, LimeLib and ShetiPhianCore)
- [x] Invalid recipe ingredients so far (ore:dustSugar -> minecraft:sugar) (ore:ingotEvil -> ore:ingotEvilMetal)
- [x] Ore duping. Ore Core nether ores dropping multiple of themselves when broken (with fortune) which can be converted to regular ores. Not sure if they generate naturally but they are spawned by Chance Cubes' magic feet effect and maybe the ore pillars.

From other threads (Just to be more compact and have a checklist):
- [x] Hidden Grout quest. Having grout in inventory (provided edit mode is disabled) will complete the quest, but it should be visible anyways. ( #12 )
- [x] Hidden Tinkers' Blocks. Legible NEI's {keep-one:[[*],[0]]}; in Tinkers'? ( #12 )
- [x] NEI causing lag on opening/closing inventory. Replace NEI with More Overlays (#11 )

**Comment by Fundryi** [comment]
U are the type of Player that every modpack creator loves xD Thank you so much for helping me!
I will work on everything as soon as im on my old Harddrive. 
Regards, Fundryi

**Comment by Fundryi** [comment]
Soo, nearly done with all of that. But I cant fix "Ore duping" with fortune enchantment :/ its mod related.
Besides that I won't remove "NEI" because I never had any issues with it and no one else reported something related to it, so I hope u are okay with this. I mean u can remove it yourself anyways xP
Also, I cant find a way to show the "Graveyard Soil" without completely disabling the Filter for Tinkers Construct. So If u wanna see it look below :p

If u wanna see every item just Press "Numpad 9" < This disabled all JEI Filters.

**Comment by jezzen** [comment]
Haha, I was just typing out some stuff for that XD.

**Comment by jezzen** [comment]
No problem, it's mainly to prevent any fixes I set up being reset and having to redo them after each update.

Speaking of which, could you use the default options mod properly and put options.txt and mod configs in it's folder and only have updated settings in the regular config folder to override? It may need some testing as I'm not too sure how it works.

As for the Ore core duping, I think I have an idea to solve that. I'm guessing the chance cube rewards that spawn them use oredict of ore*, and IRRC, Minetweaker was able to remove oredict listings from an item. I'll do a little testing on my side, but something like this should work:

val diamond = <ore:oreDiamond>;
diamond .remove(<orecore:nether_diamond_ore>);

then do it for the nether ores with oredict on them. I did a check and the end ores seem to not drop themselves.

**Comment by Fundryi** [comment]
Also if ya wanna get faster help/ or anything else u should join our Discord Server: https://discord.gg/hxVhpcU
